# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.GenericIPAddressField()),
                ('hostpwd', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(max_length=200)),
                ('svnpath', models.CharField(blank=True, max_length=200, null=True)),
                ('svnpwd', models.CharField(blank=True, max_length=200, null=True)),
                ('nginxconf', models.CharField(blank=True, max_length=200, null=True)),
                ('nginxupsteam', models.CharField(blank=True, max_length=200, null=True)),
                ('nginxsbin', models.CharField(blank=True, max_length=200, null=True)),
                ('ps', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200)),
                ('userid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='teamid',
            field=models.ManyToManyField(to='web.Team'),
        ),
        migrations.AddField(
            model_name='code',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Team'),
        ),
    ]
