# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='svnuser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
