# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160523_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='language_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Language'),
            preserve_default=False,
        ),
    ]
