# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_host_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxhost',
            name='hostname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
