# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_nginxhost_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='url',
        ),
    ]
