# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Status'),
            preserve_default=False,
        ),
    ]
