# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_host_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200)),
                ('userid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='groupname',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='host',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='host',
            name='nginxconf',
        ),
        migrations.RemoveField(
            model_name='host',
            name='nginxsbin',
        ),
        migrations.RemoveField(
            model_name='host',
            name='nginxupsteam',
        ),
        migrations.RemoveField(
            model_name='host',
            name='path',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ps',
        ),
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
        migrations.RemoveField(
            model_name='host',
            name='svnpath',
        ),
        migrations.RemoveField(
            model_name='host',
            name='svnpwd',
        ),
        migrations.RemoveField(
            model_name='host',
            name='svnuser',
        ),
        migrations.RemoveField(
            model_name='host',
            name='teamid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='userid',
        ),
        migrations.AddField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=22, max_length=20),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.CharField(default='root', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='host',
            field=models.ManyToManyField(to='web.Host'),
        ),
        migrations.AddField(
            model_name='team',
            name='language_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='nginxconf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='nginxsbin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='nginxupsteam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='ps',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='svnpath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='svnpwd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='svnuser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='teamport',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='teamid',
            field=models.ManyToManyField(to='web.TeamGroup'),
        ),
    ]
