# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160524_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=22),
        ),
    ]
