# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_monitor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='zabbixid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
