# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160524_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nginxupsteam',
            new_name='nginxupstream',
        ),
    ]
