# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_monitor_zabbixid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='zabbixid',
        ),
    ]
