# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20160524_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nginxsbin',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamid',
        ),
        migrations.AddField(
            model_name='team',
            name='teamid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.TeamGroup'),
            preserve_default=False,
        ),
    ]
