# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20160804_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('database', models.CharField(max_length=100)),
                ('maxtime', models.IntegerField()),
                ('avgtime', models.IntegerField()),
                ('sql', models.CharField(max_length=5000)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
