# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0010_auto_20160525_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgroup',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamid',
        ),
        migrations.AddField(
            model_name='team',
            name='groupname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='userid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamGroup',
        ),
    ]
