# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_slow'),
    ]

    operations = [
        migrations.AddField(
            model_name='slow',
            name='mintime',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slow',
            name='avgtime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slow',
            name='maxtime',
            field=models.CharField(max_length=100),
        ),
    ]
