# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_team_nginxhost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.GenericIPAddressField()),
                ('hostpwd', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.CharField(default='root', max_length=200)),
                ('port', models.IntegerField(default=22)),
            ],
        ),
    ]
