# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_nginxhost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='nginxhost',
        ),
        migrations.AddField(
            model_name='team',
            name='nginxhost',
            field=models.ManyToManyField(to='web.NginxHost'),
        ),
    ]
