# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20160912_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slow',
            old_name='database',
            new_name='datab',
        ),
        migrations.RenameField(
            model_name='slow',
            old_name='sql',
            new_name='insql',
        ),
    ]
