# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20160527_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxhost',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.HostStatus'),
            preserve_default=False,
        ),
    ]
