# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0016_nginxhost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
        migrations.AddField(
            model_name='code',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Status'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
        migrations.AddField(
            model_name='code',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
