# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20160527_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='update_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 30, 9, 30, 6, 999889, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
