# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20160912_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slow',
            name='avgtime',
        ),
        migrations.RemoveField(
            model_name='slow',
            name='maxtime',
        ),
        migrations.RemoveField(
            model_name='slow',
            name='mintime',
        ),
    ]
