# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20160530_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
