# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20160530_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Host'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='path',
            field=models.CharField(max_length=2000),
        ),
    ]
