# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_remove_code_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
