# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20160601_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='relat',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Code'),
        ),
        migrations.AddField(
            model_name='relat',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Host'),
        ),
        migrations.AddField(
            model_name='relat',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Status'),
        ),
    ]
