# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20160601_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='datepath',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relat',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Code'),
        ),
    ]
