# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20160602_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='relat',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Code'),
        ),
    ]
